### ISSUE TITLE
`tokens.json` 적용

### ISSUE THREAD

**Issue by manamana32321** [skku-amang/main#45]
디자인 팀에서 제안한 Tokens Studio의 파일을 전체적으로 적용합니다.

앞으로 TailwindCSS의 기본 색상 파레트 사용은 금지합니다!
성공 또는 모집 완료 색상 변경 예시: `green-500` -> `success-200`

**Comment by youngjjju** [comment]
넵

**Comment by manamana32321** [comment]
개발 방향이 변경되었습니다.
모든 컴포넌트와 속성을 정의하기 보다는
디자이너 팀의 협조로 Shadcn과 TailwindCSS를 적극 활용합니다.
